name: Push to Krew

on:
  release:
    types: [published]

jobs:
  push-to-krew:
    runs-on: ubuntu-18.04
    steps:
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38
